[package]
name = "decode-from-json"
version = "0.1.0"
edition = "2021"

[dependencies]
attohttpc = { version = "0.22.0", default-features = false }
humphrey_json = { version = "0.2.1", default-features = false, features = ["derive"] }
